# Generated by Django 4.1.6 on 2023-02-05 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog_app', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='myblog_app.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_category', to='myblog_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='books',
            name='date_publication',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='books',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Не нравится'),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to='filebooks/', verbose_name='Файл книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genry',
            field=models.ManyToManyField(related_name='books_genry', to='myblog_app.genry', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='books',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Нравится'),
        ),
        migrations.AlterField(
            model_name='books',
            name='num_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во страниц'),
        ),
        migrations.AlterField(
            model_name='books',
            name='poster',
            field=models.ImageField(upload_to='poster/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_publisher', to='myblog_app.publisher', verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='books',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
