# Generated by Django 4.1.6 on 2023-02-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_app', '0004_books_permit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='genry',
            new_name='genrys',
        ),
    ]
