# Generated by Django 4.1.6 on 2023-02-08 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_app', '0005_rename_author_books_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_created_post',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='books',
            name='date_publication',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата издания книги'),
        ),
    ]
